title: Kids Chant
author: Veronica Brandt
email: veronica@kidschant.com
description: > # this means to ignore newlines until "baseurl:"
     Passing on Gregorian Chant to Kids

twitter_username: veromarybrrr
github_username:  veromary

sass:
    style: compressed

header_pages:
    - pater.html
    - rosary/index.md
